Document: hadoop-lzo
Title: Debian hadoop-lzo Manual
Author: <insert document author here>
Abstract: This manual describes what hadoop-lzo is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hadoop-lzo/hadoop-lzo.sgml.gz

Format: postscript
Files: /usr/share/doc/hadoop-lzo/hadoop-lzo.ps.gz

Format: text
Files: /usr/share/doc/hadoop-lzo/hadoop-lzo.text.gz

Format: HTML
Index: /usr/share/doc/hadoop-lzo/html/index.html
Files: /usr/share/doc/hadoop-lzo/html/*.html
